export const dummyArtist = [
  {
    id: 1,
    type: "artist",
    title: "예술가 이름",
    isStar: true,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울시 성북구 OO동 OO",
    category: "밴드 셋 솔로 셋",
  },
  {
    id: 2,
    type: "artist",
    title: "예술가 이름",
    isStar: false,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울 전체 인천 전체",
    category: "밴드 셋",
  },
  {
    id: 3,
    type: "artist",
    title: "예술가 이름",
    isStar: false,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울 전체 인천 전체",
    category: "밴드 셋",
  },
  {
    id: 4,
    type: "artist",
    title: "예술가 이름",
    isStar: false,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울 전체 인천 전체",
    category: "밴드 셋",
  },
  {
    id: 5,
    type: "artist",
    title: "예술가 이름",
    isStar: false,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울 전체 인천 전체",
    category: "밴드 셋",
  },
  {
    id: 6,
    type: "artist",
    title: "예술가 이름",
    isStar: false,
    img: "https://www.gyeongju.go.kr/upload/content/thumb/gyimage/%EC%B2%A8%EC%84%B1%EB%8C%80%EC%9D%98%20%EC%95%84%EB%A6%84%EB%8B%A4%EC%9B%80.jpg",
    place: "서울 전체 인천 전체",
    category: "밴드 셋",
  },
];
