import type { UserProfile } from "@types";

export const mockArtists: UserProfile[] = [
  {
    role: "artist",
    id: 1,
    userId: 101,
    name: "인디밴드 새벽",
    bio: "인디/얼터너티브 중심으로 활동하는 4인조 밴드",
    numberOfMembers: 4,
    categoryId: 2,
    categoryName: "밴드",
    customCategory: "라틴댄스",
    equipments: ["마이크", "기타 앰프"],
    portfolioLinks: [
      "https://youtube.com/@band",
      "https://soundcloud.com/band",
    ],
    profileImageUrl: "https://example.com/artist1.jpg",
    region: ["서울 마포구", "서울 서대문구"],
    desiredPay: 300000,
    isFreeAllowed: false,
    phoneNumber: "01012345678",
    createdAt: "2025-09-06T13:34:54.873888Z",
  },
  {
    role: "artist",
    id: 2,
    userId: 102,
    name: "재즈 싱어 민아",
    bio: "재즈와 보사노바를 주로 부르는 보컬리스트",
    numberOfMembers: 1,
    categoryId: 5,
    categoryName: "보컬",
    equipments: ["피아노", "스탠드 마이크"],
    portfolioLinks: ["https://instagram.com/jazzmina"],
    profileImageUrl: "https://example.com/artist2.jpg",
    region: ["서울 강남구"],
    desiredPay: 200000,
    isFreeAllowed: true,
    phoneNumber: "01087654321",
    createdAt: "2025-09-07T10:15:32.120Z",
  },
];

export const mockSpaces: UserProfile[] = [
  {
    role: "space",
    id: 1,
    userId: 201,
    placeName: "서프록 라운지 홍대점",
    address: "서울 마포구 와우산로",
    postalCode: "04000",
    kakaoMapLink: "http://map.kakao.com/link/홍대",
    category: "재즈바",
    description: "아늑한 공연 공간으로 30석 규모",
    capacitySeated: 30,
    capacityStanding: 60,
    preferredCategories: [1, 3, 5],
    businessNumber: "123-45-67890",
    atmosphere: ["편안함", "아늑함"],
    placeRegion: "서울 마포구",
    placeImageUrl: "http://example.com/space1.jpg",
    equipments: ["마이크", "스피커"],
    phoneNumber: "01011312222",
    createdAt: new Date("2025-09-06T16:00:37.820Z"),
  },
  {
    role: "space",
    id: 2,
    userId: 202,
    placeName: "예술극장 대학로",
    address: "서울 종로구 대학로",
    postalCode: "03000",
    category: "소극장",
    description: "연극과 공연을 위한 100석 규모의 극장",
    capacitySeated: 100,
    capacityStanding: 0,
    preferredCategories: [2, 4],
    businessNumber: "987-65-43210",
    atmosphere: ["진지함", "클래식"],
    placeRegion: "서울 종로구",
    placeImageUrl: "http://example.com/space2.jpg",
    equipments: ["조명", "음향 장비"],
    phoneNumber: "01099998888",
    createdAt: new Date("2025-09-08T09:45:21.000Z"),
  },
];
